// resources/js/src/student/components/Dashboard/UpcomingBookings.tsx
import React from 'react';
import { useApp } from '@/shared/contexts/AppContext';
import { Calendar, Clock, MapPin } from 'lucide-react';
import { format } from 'date-fns';

const UpcomingBookings: React.FC = () => {
  const { bookings, libraries, seats } = useApp();

  const upcomingBookings = bookings
    .filter(booking => booking.status === 'upcoming')
    .slice(0, 3);

  const getLibraryName = (libraryId: string) => {
    return libraries.find(lib => lib.id === libraryId)?.name || 'Unknown Library';
  };

  const getSeatNumber = (seatId: string) => {
    return seats.find(seat => seat.id === seatId)?.seatNumber || 'Unknown Seat';
  };

  return (
    <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-6">
      <h2 className="text-lg font-semibold text-gray-800 mb-4 flex items-center">
        <Calendar className="w-5 h-5 mr-2 text-blue-600" />
        Upcoming Bookings
      </h2>
      
      {upcomingBookings.length === 0 ? (
        <div className="text-center py-8">
          <Calendar className="w-12 h-12 text-gray-300 mx-auto mb-3" />
          <p className="text-gray-500 text-sm">No upcoming bookings</p>
          <p className="text-gray-400 text-xs mt-1">Book a seat to get started!</p>
        </div>
      ) : (
        <div className="space-y-3">
          {upcomingBookings.map((booking) => (
            <div key={booking.id} className="p-3 bg-gray-50 rounded-lg border border-gray-200">
              <div className="flex items-center justify-between mb-2">
                <h3 className="font-medium text-gray-800 text-sm">
                  Seat {getSeatNumber(booking.seatId)}
                </h3>
                <span className="text-xs text-blue-600 bg-blue-100 px-2 py-1 rounded-full">
                  {booking.status}
                </span>
              </div>
              
              <div className="space-y-1 text-xs text-gray-600">
                <div className="flex items-center">
                  <MapPin className="w-3 h-3 mr-1" />
                  {getLibraryName(booking.libraryId)}
                </div>
                <div className="flex items-center">
                  <Calendar className="w-3 h-3 mr-1" />
                  {booking.date}
                </div>
                <div className="flex items-center">
                  <Clock className="w-3 h-3 mr-1" />
                  {booking.startTime} - {booking.endTime}
                </div>
              </div>
              
              {!booking.checkedIn && (
                <div className="mt-2 pt-2 border-t border-gray-200">
                  <button className="text-xs text-blue-600 hover:text-blue-700 font-medium">
                    Check In with QR
                  </button>
                </div>
              )}
            </div>
          ))}
        </div>
      )}
    </div>
  );
};

export default UpcomingBookings;

// resources/js/src/student/components/Dashboard/UpcomingBookings.vue
<template>
  <div class="bg-white rounded-xl shadow-sm border border-gray-200 p-6">
    <h2 class="text-lg font-bold text-gray-800 mb-4 flex items-center">
      <Calendar class="w-5 h-5 mr-2 text-blue-600" />
      Active & Upcoming
    </h2>
    
    <div v-if="activeBookings.length === 0" class="text-center py-8">
      <div class="w-12 h-12 bg-gray-50 rounded-full flex items-center justify-center mx-auto mb-3">
        <Calendar class="w-6 h-6 text-gray-300" />
      </div>
      <p class="text-gray-500 text-sm">No active bookings</p>
      <router-link to="/student/libraries" class="text-xs text-blue-600 hover:underline mt-2 inline-block">Book a seat now</router-link>
    </div>

    <div v-else class="space-y-4">
      <div 
        v-for="booking in activeBookings" 
        :key="booking.id" 
        class="p-4 bg-gray-50 rounded-xl border border-gray-100 hover:border-blue-100 transition-colors group"
      >
        <div class="flex items-center justify-between mb-3">
          <div class="flex items-center">
            <div class="p-2 bg-white rounded-lg shadow-sm mr-3 group-hover:text-blue-600">
              <Armchair class="w-4 h-4" />
            </div>
            <div>
              <h3 class="font-bold text-gray-800 text-sm">
                Seat {{ booking.seat?.seat_number }}
              </h3>
              <p class="text-[10px] text-gray-400 font-bold uppercase tracking-wider">
                {{ booking.status === 'checked_in' ? 'Active Now' : 'Reserved' }}
              </p>
            </div>
          </div>
          <div class="text-right">
            <p class="text-[10px] text-gray-400 font-bold uppercase">Remaining</p>
            <p class="text-sm font-black text-blue-600 font-mono">{{ getRemainingTime(booking) }}</p>
          </div>
        </div>
        
        <div class="space-y-2 text-xs text-gray-600">
          <div class="flex items-center">
            <MapPin class="w-3.5 h-3.5 mr-2 text-gray-400" />
            {{ booking.seat?.library?.name }}
          </div>
          <div class="flex items-center">
            <Clock class="w-3.5 h-3.5 mr-2 text-gray-400" />
            {{ formatTime(booking.booking_time) }} - {{ formatTime(booking.scheduled_end_time) }}
          </div>
          <div class="flex flex-wrap gap-2 mt-1">
            <span v-if="booking.seat?.has_computer" class="flex items-center text-[9px] bg-blue-50 text-blue-600 px-1.5 py-0.5 rounded-md">
              <Monitor class="w-2.5 h-2.5 mr-1" /> PC
            </span>
            <span v-if="booking.seat?.near_window" class="flex items-center text-[9px] bg-yellow-50 text-yellow-700 px-1.5 py-0.5 rounded-md">
              <Layout class="w-2.5 h-2.5 mr-1" /> Window
            </span>
            <span v-if="booking.seat?.socket_count > 0" class="flex items-center text-[9px] bg-green-50 text-green-700 px-1.5 py-0.5 rounded-md">
              <Zap class="w-2.5 h-2.5 mr-1" /> {{ booking.seat.socket_count }} Sockets
            </span>
          </div>
        </div>
        
        <div class="mt-4 flex gap-2">
          <button 
            v-if="booking.status === 'booked'"
            @click="handleCheckIn(booking.id)"
            class="flex-1 py-2 bg-blue-600 text-white rounded-lg text-xs font-bold hover:bg-blue-700 transition-colors shadow-sm"
          >
            Check In
          </button>
          <button 
            v-if="booking.status === 'booked'"
            @click="handleCancel(booking.id)"
            class="flex-1 py-2 bg-red-600 text-white rounded-lg text-xs font-bold hover:bg-red-700 transition-colors shadow-sm"
          >
            Cancel
          </button>
          <button 
            v-if="booking.status === 'checked_in'"
            @click="handleCheckOut(booking.id)"
            class="flex-1 py-2 bg-orange-600 text-white rounded-lg text-xs font-bold hover:bg-orange-700 transition-colors shadow-sm"
          >
            Check Out
          </button>
        </div>
      </div>
    </div>


  </div>
</template>

<script setup lang="ts">
import { computed, ref, onMounted, onUnmounted, watch } from 'vue';
import { useApp } from '@/shared/composables/useApp';
import { Calendar, Clock, MapPin, Armchair, Monitor, Zap, Layout } from 'lucide-vue-next';

const { bookings, loadBookings, checkInSeat, checkOutSeat, extendSeatBooking, cancelBooking } = useApp();
const now = ref(new Date());
let timer: any = null;



const activeBookings = computed(() => 
  bookings.value
    .filter(b => b.status === 'booked' || b.status === 'checked_in')
    .slice(0, 3)
);





const getRemainingTime = (booking: any) => {
  const end = new Date(booking.scheduled_end_time);
  const diff = end.getTime() - now.value.getTime();
  
  if (diff <= 0) return '00:00:00';
  
  const h = Math.floor(diff / 3600000);
  const m = Math.floor((diff % 3600000) / 60000);
  const s = Math.floor((diff % 60000) / 1000);
  
  return `${h.toString().padStart(2, '0')}:${m.toString().padStart(2, '0')}:${s.toString().padStart(2, '0')}`;
};

const formatTime = (dateStr: string) => {
  return new Date(dateStr).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
};

const handleCheckIn = async (id: number) => {
  if (confirm('Check in to this seat?')) {
    await checkInSeat(id, 'MOCK_QR');
    await loadBookings();
  }
};

const handleCheckOut = async (id: number) => {
  if (confirm('Check out from this seat?')) {
    await checkOutSeat(id);
    await loadBookings();
  }
};

const handleCancel = async (id: number) => {
  if (confirm('Are you sure you want to cancel this booking?')) {
    await cancelBooking(id);
  }
};

onMounted(() => {
  timer = setInterval(() => {
    now.value = new Date();
  }, 1000);
});

onUnmounted(() => {
  if (timer) clearInterval(timer);
});
</script>
